name: currencyapp
description: "Currency Converter App"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Storage & Connectivity
  drift: ^2.27.0
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5
  connectivity_plus: ^6.1.4

  # State Management
  flutter_bloc: ^9.1.1 # BLoC pattern implementation for Flutter
  equatable: ^2.0.7 # Simplifies equality comparisons for classes
  hydrated_bloc: ^10.1.1 # Persist BLoC state across app restarts

  # Networking
  dio: ^5.8.0+1 # HTTP client for API requests
  retrofit: ^4.6.0 # Type-safe HTTP client generator
  pretty_dio_logger: ^1.4.0 # Logger for Dio HTTP requests and responses

  # Dependency Injection
  get_it: ^8.0.3 # Service locator for dependency injection

  # Data Serialization & Code Generation
  json_annotation: ^4.9.0 # Annotations for JSON serialization
  freezed_annotation: ^3.1.0 # Annotations for Freezed
  freezed: ^3.1.0 # Code generation for immutable classes

  # UI Components & Styling
  flutter_svg: ^2.2.0 # SVG rendering support
  cupertino_icons: ^1.0.8 # iOS-style icons
  skeletonizer: ^2.1.0+1 # Skeleton loading screens
  scaled_app: ^2.3.0 # Scaled app for responsive designs
  toastification: ^3.0.3 # Toastification for showing toast messages

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5 # JSON serialization code generator
  retrofit_generator: ^9.1.5 # Code generator for Retrofit

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
